# Use the official Node.js image as the base image
FROM node:20

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the NuxtJS application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the NuxtJS server
CMD ["node", "app/.output/server/index.mjs"]
