version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=3000
      - DBURL=mongodb://mongo:27017/ou-lunch
      - DBNAME=ou-lunch
    depends_on:
      - mongo
    networks:
      - ouf_internal_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - NUXT_API_URL=http://backend:3000
    ports:
      - ":3000"
    depends_on:
      - backend
      - mongo
    networks:
      - ouf_internal_network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
        - ouf_internal_network

volumes:
  mongo-data:

networks:
  ouf_internal_network:
    driver: bridge
