version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NUXT_PUBLIC_U_SCRIPT=${U_SCRIPT}
      - NUXT_PUBLIC_U_ID=${U_ID}
      - NUXT_DB_URL=mongodb://mongo:27017/ou-lunch
      - NUXT_DB_NAME=ou-lunch
    depends_on:
      - mongo
    healthcheck:
      test: curl --fail http://127.0.0.1:3000 || exit 1
      interval: 10s
      timeout: 20s
      retries: 10

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
