version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=3000
      - DBURL=mongodb://mongo:27017/ou-lunch
      - DBNAME=ou-lunch
    depends_on:
      - mongo
    healthcheck:
      test: curl --fail http://127.0.0.1:3000/api/menu || exit 1
      interval: 10s
      timeout: 20s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - NUXT_API_URL=http://backend:3000
      - NUXT_PUBLIC_U_SCRIPT=${U_SCRIPT}
      - NUXT_PUBLIC_U_ID=${U_ID}
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - mongo
    healthcheck:
      test: curl --fail http://127.0.0.1:3000 || exit 1
      interval: 10s
      timeout: 20s
      retries: 10

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
