openapi: 3.0.0
info:
  title: Oulu University Food API
  version: 1.0.0
  description: API for getting restaurant menus at the University of Oulu
paths:
  /api/menu:
    get:
      summary: Get all restaurants
      responses:
        '200':
          description: A list of restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
components:
  schemas:
    Restaurant:
      type: object
      required:
        - name
        - url
        - campus
        - menu
      properties:
        name:
          type: string
          description: Restaurant name
        url:
          type: string
          description: Restaurant URL
        campus:
          type: string
          description: Campus
        menu:
          type: array
          description: Menus for the restaurant
          items:
            type: object
            required:
              - date
              - en
              - fi
            properties:
              date:
                type: string
                format: date
                description: Date of the menu
              en:
                $ref: '#/components/schemas/MenuItems'
              fi:
                $ref: '#/components/schemas/MenuItems'
    MenuItems:
      type: array
      description: Menu items
      items:
        type: object
        required:
          - name
          - items
        properties:
          name:
            type: string
            description: Menu option name
            example: Lunch 1
          items:
            type: array
            description: Menu items
            items:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Item name
                diets:
                  type: string
                  description: Dietary restrictions
                ingredients:
                  type: string
                  description: Ingredients
